---
title: "Plot Results"
author: "Lin Zhou, August 2022"
---

# import posterior estimations
```{r} 
rm(list=ls())

library(dplyr) 
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(reshape2)
library(colorspace)
source("../src/data_loader.R")
source("../src/jags_functions.R")

sub_list <- list(  # for n-of-1 trials, select only one subject!
  "sub_01",
  "sub_02",
  "sub_03",
  "sub_05",
  "sub_06",
  "sub_07",
  "sub_08",
  "sub_09",
  "sub_10",
  "sub_11",
  "sub_12",
  "sub_13",
  "sub_14",
  "sub_15",
  "sub_17",
  "sub_18"
  )

var_list <- list(
  list("stride_lengths", "SL"),
  list("stride_times", "ST")
  )

# # read posterior estimations from file
model <- "AR1"
downsample_n <- 5
read_path <- file.path("..", "data", "processed", paste0("all_left_foot_downsample_", downsample_n))

all_estimate_df <- data.frame()
for (var in var_list) {
  for (sub in sub_list) {
    data.r2jags <- get(load(file.path(read_path, paste0("data_r2jags_AR1_diff_prob_", var[[2]], "_", sub, ".RData"))))
    all_estimate_df <- bind_rows(all_estimate_df, get_jags_table(data.r2jags, sub, var[[1]]))
  }
  
}

```

Get distributions of all 4 conditions
```{r}
beta1 <- filter(all_estimate_df, parameter == "beta[1]")
beta2 <- filter(all_estimate_df, parameter == "beta[2]")
beta3 <- filter(all_estimate_df, parameter == "beta[3]")
beta4 <- filter(all_estimate_df, parameter == "beta[4]")

conditions_df <- beta1[, c("sub", "var")]

value <- "mean"
conditions_df["st_control"] <- beta1[value]
conditions_df["st_fatigue"] <- beta1[value] + beta3[value]
conditions_df["dt_control"] <- beta1[value] + beta2[value]
conditions_df["dt_fatigue"] <- beta1[value] + beta2[value] + beta3[value] + beta4[value]
conditions_df_mean <- gather(conditions_df, key = "condition", value = "mean",
                          st_control, st_fatigue, dt_control, dt_fatigue)

value <- "sd"
conditions_df["st_control"] <- sqrt(beta1[value]^2)
conditions_df["st_fatigue"] <- sqrt(beta1[value]^2 + beta3[value]^2)
conditions_df["dt_control"] <- sqrt(beta1[value]^2 + beta2[value]^2)
conditions_df["dt_fatigue"] <- sqrt(beta1[value]^2 + beta2[value]^2 + beta3[value]^2 + beta4[value]^2)
conditions_df_sd <- gather(conditions_df, key = "condition", value = "sd",
                          st_control, st_fatigue, dt_control, dt_fatigue)

plot_df <- merge(conditions_df_mean, conditions_df_sd)

# add mean over all subjects
conditions_df_mean_all <- aggregate(mean~condition+var, conditions_df_mean, mean)
conditions_df_mean_all["sub"] <- "all"

# add sd of means over all subjects
conditions_df_sd_all<- aggregate(mean~condition+var, conditions_df_mean, sd)  # SD of means
names(conditions_df_sd_all)[names(conditions_df_sd_all) == 'mean'] <- 'sd'
conditions_df_sd_all["sub"] <- "all"

conditions_df_all <- merge(conditions_df_mean_all, conditions_df_sd_all)

# put all dataframes together
plot_df <- bind_rows(plot_df, conditions_df_all)

# save estimated parameters table
write.csv(
plot_df, 
file = file.path(read_path, paste0("all_estimates_gait_parameters_", model, ".csv")), 
row.names=FALSE
)

# rename for plotting
plot_df <- plot_df %>% 
  rename(
    Participant = sub,
    Condition = condition
    )
plot_df[plot_df == "stride_lengths"] <- "Stride Length [m]"
plot_df[plot_df == "stride_times"] <- "Stride Time [s]"
plot_df[plot_df == "st_control"] <- "ST-Control"
plot_df[plot_df == "st_fatigue"] <- "ST-Fatigue"
plot_df[plot_df == "dt_control"] <- "DT-Control"
plot_df[plot_df == "dt_fatigue"] <- "DT-Fatigue"
plot_df[plot_df == "all"] <- "All"

```

```{r, fig.width = 7, fig.height = 5}
fig_posterior <- ggplot(plot_df, aes(x = Participant, fill = Condition)) +
  geom_boxplot(aes(ymin =mean-3*sd, lower = mean-sd, middle = mean, upper = mean+sd, ymax = mean+3*sd),
               stat = "identity", width=0.6) +
  ylab("Posterior Estimates") +
  scale_fill_brewer(palette="Spectral") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.6))
fig_posterior2 <- fig_posterior + facet_wrap(vars(var), nrow = 2, strip.position = "left", scales = "free_y") +
  theme(strip.background=element_rect( fill="white"), 
        strip.placement = "outside",
        panel.spacing.y = unit(1, "lines")
        )
  
print(fig_posterior2)
```

Summary of the observed data
```{r, fig.width = 7, fig.height = 5}
all_observations_df <- read_csv(file.path("..", "data", "processed", "features", "df_all.csv"), show_col_types = FALSE)
all_observations_df <- downsample_rows(all_observations_df[all_observations_df$foot == "left", ], downsample_n) # reduce data size to match the data used for JAGS models
all_observations_df["conditions"] <- paste(all_observations_df$condition, all_observations_df$fatigue, sep="_")

# add mean over all subjects
all_observations_df_all <- all_observations_df
all_observations_df_all["sub"] <- "All"
all_observations_df <- rbind(all_observations_df, all_observations_df_all)

# melt gait parameters of interest into one column for facet plot
all_observations_df <- melt(all_observations_df, id.vars = c("sub", "conditions"), measure.vars = c("stride_lengths","stride_times"))
all_observations_df$variable <- as.character(all_observations_df$variable)

# rename for plotting
all_observations_df <- all_observations_df %>% 
  rename(
    Participant = sub,
    Condition = conditions
    )
all_observations_df[all_observations_df == "st_control"] <- "ST-Control"
all_observations_df[all_observations_df == "st_fatigue"] <- "ST-Fatigue"
all_observations_df[all_observations_df == "dt_control"] <- "DT-Control"
all_observations_df[all_observations_df == "dt_fatigue"] <- "DT-Fatigue"
all_observations_df[all_observations_df == "stride_lengths"] <- "Stride Length [m]"
all_observations_df[all_observations_df == "stride_times"] <- "Stride Time [s]"

fig_observation <- ggplot(all_observations_df, aes(x = Participant, y=value, fill = Condition)) +
  geom_boxplot(width=0.6) +
  ylab("Observed Values") +
  scale_fill_brewer(palette="Spectral") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.6))
  
fig_observation2 <- fig_observation + facet_wrap(vars(variable), nrow = 2, strip.position = "left", scales = "free_y") +
  theme(strip.background=element_rect( fill="white"), 
        strip.placement = "outside",
        panel.spacing.y = unit(1, "lines")
        )
print(fig_observation2)

```
Posterior Predictive Check:
Combine Posterior with Observations
```{r, fig.width = 8, fig.height = 6}

for (var in list("Stride Length [m]", "Stride Time [s]")) {
  fig_observation_var <- ggplot(all_observations_df[all_observations_df$variable == var,], 
                                aes(x = Participant, 
                                    y=value, 
                                    fill = Condition
                                    )) +
    geom_boxplot(width=0.6) +
    ylab(var) +
    scale_fill_brewer(palette="Spectral") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust=0.6))
  
  fig_posterior_var <- ggplot(plot_df[plot_df$var == var,], aes(x = Participant, fill = Condition)) +
    geom_boxplot(aes(ymin =mean-3*sd, lower = mean-sd, middle = mean, upper = mean+sd, ymax = mean+3*sd),
                 stat = "identity", width=0.6) +
    ylab(var) +
    scale_fill_brewer(palette="Spectral") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust=0.6),
          plot.margin = unit(c(0.5,0.5,2,0.5), "lines"))
  
  fig_combined <- ggarrange(fig_posterior_var, fig_observation_var,
                      labels = c("A", "B"),
                      ncol = 1, nrow = 2,
                      heights = c(1, 0.9)
                      )
  print(fig_combined)
}

```

Heatmap of the gait parameter changes
```{r}
vars <- list("stride_lengths", "stride_times")

# rename conditions for plotting
conditions_df_mean[conditions_df_mean == "st_control"] <- "ST-Control"
conditions_df_mean[conditions_df_mean == "st_fatigue"] <- "ST-Fatigue"
conditions_df_mean[conditions_df_mean == "dt_control"] <- "DT-Control"
conditions_df_mean[conditions_df_mean == "dt_fatigue"] <- "DT-Fatigue"

# generate unique combinations of the conditions
cond_table <- table(unique(conditions_df_all["condition"]))
idx_comb <- combn(unique(c(1, 2, 3, 4)),2)

diff_df_subs <- list()
diff_df_params <- list()
subs <-  unique(conditions_df_mean$sub)
for (j in 1:length(vars)) {
  for (i in 1:length(subs)) {
  sub_df <- conditions_df_mean[conditions_df_mean$sub == subs[i] & conditions_df_mean$var == vars[[j]], ]
  diff <- sub_df$mean[unlist(idx_comb[1,])] - sub_df$mean[unlist(idx_comb[2,])]
  diff_names <- paste(sub_df$condition[unlist(idx_comb[1,])], sub_df$condition[unlist(idx_comb[2,])], sep=" - ")
  sub_diff_df <- as.data.frame(setNames(diff, diff_names))  # create dataframe for this subject
  names(sub_diff_df) <- subs[i]  # rename column to subject
  diff_df_subs[[i]] <- sub_diff_df
  }
  diff_df <- cbind.data.frame(diff_df_subs)
  diff_df$cond_diff <- rownames(diff_df)
  diff_df_plot_var <- gather(diff_df, sub, value, sub_01:sub_18, factor_key=TRUE)
  # browser()
  diff_df_plot_var["variable"] <- vars[[j]]
  diff_df_params[[j]] <- diff_df_plot_var
}
diff_df_plot <- bind_rows(diff_df_params)

# rename for plotting
diff_df_plot <- diff_df_plot %>% 
  rename(
    Participant = sub,
    Conditions = cond_diff,
    Difference = value
    )
diff_df_plot[diff_df_plot == "stride_lengths"] <- "Stride Length [m]"
diff_df_plot[diff_df_plot == "stride_times"] <- "Stride Time [s]"

fig_diff <- ggplot(diff_df_plot, aes(Participant, Conditions, fill = Difference)) + 
  geom_tile(color="white") +
  coord_equal() +
  theme_bw() +
  scale_fill_continuous_divergingx(palette = 'Spectral', mid = 0, l1 = 0, l3 = 0, p3 = 0.8, p4 = 0.6) +
  theme(axis.text.x = element_text(vjust=0.6, angle = 45))

fig_diff2 <- fig_diff + facet_grid(rows = vars(variable), switch = "y") +
  theme(strip.background=element_rect( fill="white"),
        strip.placement = "outside",
        panel.spacing.y = unit(1, "lines")
        )

print(fig_diff2)

```

Probability of meaningful change
```{r, fig.width = 8, fig.height = 4}
library(svglite)
# rename variables for plotting
all_estimate_df[all_estimate_df == "stride_lengths"] <- "Stride Length"
all_estimate_df[all_estimate_df == "stride_times"] <- "Stride Time"
diff_fatigue_plot_df[diff_fatigue_plot_df == "stride_lengths"] <- "Stride Length"
diff_fatigue_plot_df[diff_fatigue_plot_df == "stride_times"] <- "Stride Time"

# plot posterior probabilities
h_lines <- data.frame(
  var = c("Stride Length", "Stride Time"), 
  threshold = c(0.3, 0.2)
  )

fig_posterior_prob <- ggplot(filter(all_estimate_df, (parameter == 'p1'))) +
  geom_boxplot(aes(x=sub, group=sub, ymin =mean-3*sd, lower = mean-sd, middle = mean, upper = mean+sd, ymax = mean+3*sd),
                 stat = "identity", width=0.6) +
  geom_point(data = diff_fatigue_plot_df, aes(x=sub, y=value * 10, color = var)) +
  geom_hline(data = h_lines, aes(yintercept = threshold, color = var)) +
  scale_y_continuous(
    "Probability of Meaningful Change", 
    sec.axis = sec_axis(~ . * 0.10, name = "Mean Absolute Change (%)")
  ) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.6),
        axis.text.y.right = element_text(color = "cyan4")) +
  facet_grid(rows = vars(var), switch = "y") +
  theme(strip.background=element_rect(fill="white"),
        strip.placement = "outside",
        panel.spacing.y = unit(1, "lines")
        ) +
  labs(color='Change Threshold and Values', x = 'Participant')

print(fig_posterior_prob)
ggsave(file="test.svg", plot=fig_posterior_prob, width=8, height=4)
```


```{r, fig.width = 8, fig.height = 5}
# plot posterior probabilities
fig_posterior_prob <- ggplot(filter(all_estimate_df, parameter == 'p1')) +
  geom_boxplot(aes(x=as.factor(sub), fill=var, ymin =mean-3*sd, lower = mean-sd, middle = mean, upper = mean+sd, ymax = mean+3*sd),
                 stat = "identity", width=0.6) +
  # geom_bar(position=position_dodge(), stat="identity", colour='black') +
  # geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,position=position_dodge(.9)) +
  ggtitle('Posterior probablity of meangful change after fatigue') +
  ylab("Probability") +
  # scale_fill_brewer(palette="Spectral") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.6))

# calculate mean changes from the observed data
diff_fatigue_df <- data.frame()
for (variable in var_list) {
  diff_fatigue <- list()
  for (subject in sub_list) {
    df <- filter(conditions_df_mean, (var == variable[[1]] & sub == subject))
    df_spread <- spread(df, key = condition, value = mean)
    diff_fatigue <- append(diff_fatigue, abs(df_spread$st_fatigue + df_spread$dt_fatigue - df_spread$st_control - df_spread$dt_control)/(df_spread$st_control + df_spread$dt_control))
  }
  diff_fatigue_df <- bind_rows(diff_fatigue_df, as.data.frame(diff_fatigue, col.names = sub_list, row.names = variable[[1]]))
  diff_fatigue_df$var <- rownames(diff_fatigue_df)
}

diff_fatigue_plot_df <- melt(diff_fatigue_df, id.vars = 'var', variable.name = 'sub')

# plot mean changes from the posterior estimates
fig_posterior_diff_fatigue <- ggplot(diff_fatigue_plot_df, aes(x=as.factor(sub), y=value, color = var)) +
  geom_point() +
  # geom_bar(position=position_dodge(), stat="identity", colour='black') + 
  geom_hline(yintercept = 0.03, color = 'tomato') +
  geom_hline(yintercept = 0.02, color = 'cyan4') +
  ylab("Mean absolute change (%)") +
  ggtitle('Mean absolute change after fatigue from observed data') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.6))

# combine the two plots
fig_combined <- ggarrange(fig_posterior_prob, fig_posterior_diff_fatigue,
                      labels = c("A", "B"),
                      ncol = 1, nrow = 2,
                      heights = c(1, 0.9)
                      )
print(fig_combined)
  
```
